name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build babyrite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build babyrite
        run: cargo build --verbose

      # - name: test babyrite
      #   run: cargo test --verbose
