name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Tag"
        required: true
        default: "v"
      babyrite:
        description: "babyrite tag (YYYY.R)"
        required: true
        default: "2023."

jobs:
  build_and_push:
    name: Build and Push babyrite
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup - qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup - buildx
        uses: docker/setup-buildx-action@v2

      - name: Login GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          labels: |
            org.opencontainers.image.source = https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository }}:${{ vars.BABYRITE_MAJOR }}
  release:
    name: Release Tag
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
          git tag '${{ github.event.inputs.version }}(${{ github.event.inputs.babyrite }})'
          git push origin '${{ github.event.inputs.version }}(${{ github.event.inputs.babyrite }})'
